# -*- coding: utf-8 -*-
"""Proyecto de Alvaro R.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1cEyJo8c8jdxPy-GplXcYxoHgzg97c0
"""

# Commented out IPython magic to ensure Python compatibility.
# %lsmagic

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

!pip install rpy2==3.5.1

# Commented out IPython magic to ensure Python compatibility.
# %%R
# x <- seq(0, 2*pi, length.out=500)
# sqrt(x*x)

A=435809304850943

! echo $A

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages("party")

import pandas as pd
import numpy as np

ventas = pd.DataFrame(
    {
        "ci": np.array([6060789,1178421]),
        "producto": pd.Categorical(["camaras","alarmas"]),
        "tipo_producto": pd.Categorical(["dahua","paradox"]),
        "precio": np.array([400,800]),
        "fecha": pd.to_datetime(pd.Series(["2022-06-22", "2022-07-14"]))
    }
)


ventas
 

preferencias = pd.DataFrame(
    {
        "ci": np.array([6060789,1178421,7891135,6969585]),
        "dato_pref": pd.Categorical(["ofertas","novedades","precio","calidad"]),
        "fecha": pd.to_datetime(pd.Series(["2022-02-02", "2022-05-04", "2022-04-29", "2022-04-07"]))
    }
)

preferencias



clientes= pd.DataFrame(
        {
        "ci": np.array([6060789,1178421,7891135,6969585]),
        "nombre": pd.Categorical(["Juan","Gustavo","Gabriel","Ramiro"]),
        "apellido": pd.Categorical(["Hernandez", "Gonzalez", "Salazar", "Perez"])
    }
)
 

clientes



busquedas = pd.DataFrame(
    {
        "ci": np.array([6060789,6969585]),
        "producto": pd.Categorical(["camaras","alarmas"]),
        "tipo_producto": pd.Categorical(["dahua","hikivision"]),
        "fecha": pd.to_datetime(pd.Series(["2022-05-12", "2022-07-20"]))
    }
)


busquedas

#Generador de Ejemplos
import pandas as pd
import numpy as np
import random

random.seed(100)
productos=["camaras","alarmas","monitores","extensiones"]
tipo_producto={f"{x}_{i}":[x,100*random.randint(2,8)] for i in range(10) for x in productos}
Nombres=["Maria","Jose","Juan","Luis","Rosa","Carlos","Jorge","Victor","Carmen","Pedro","Francisco","Juana"]
Apellidos=["Alvarez","Dominguez","Garcia","Gonzalez","Hernandez","Lopez","Perez","Rodriguez","Sanchez"]

##Identificadores para los clientes
uuid=[random.randint(6000000,7000000) for i in range(108) ]
S=[x+" "+y for x in Nombres for y in Apellidos]
##Clientes con identificador , nombre y apellidos.
Clientes={z:u for z,u in zip(uuid,S)}

Clientes
#Generando la tabla clientes
with open("clientes.csv","w") as archivo:
    archivo.write("ci,nombre,apellido\n")
    for x in Clientes:
        y=Clientes[x]
        U=y.split(" ")
        archivo.write(f"{x},{U[0]},{U[1]}")
        archivo.write("\n")


fechas=[f"2022-0{x}-{'0'*int(y<10)}{y}" for x in range(4,7) for y in range(1,30)]
"2022-06-22"
##Generador de tendencias de ventas y busquedas

#Generando la tabla ventas
def GeneraVentas(productos,uuid,tipo_producto,fechas):
    n=len(fechas)
    E=[]
    V=random.sample(uuid,n)
    for i,x in enumerate(fechas):
        tp=random.sample(list(tipo_producto),1)[0]
        pre=tipo_producto[tp][1]
        pro=tipo_producto[tp][0]
        E+=[[V[i],pro,tp,pre,x]]
    return E



W=GeneraVentas(productos,uuid,tipo_producto,fechas)
def GeneraBusquedas(productos,uuid,tipo_producto,fechas):
    n=len(fechas)
    E=[]
    V=random.sample(uuid,n)
    for i,x in enumerate(fechas):
        tp=random.sample(list(tipo_producto),1)[0]
        pro=tipo_producto[tp][0]
        E+=[[V[i],pro,tp,x]]
    return E

W=GeneraVentas(productos,uuid,tipo_producto,fechas)

with open("ventas.csv","w") as archivo:
    archivo.write("ci,producto,tipo_producto,precio,fecha\n")
    for c in W:
        archivo.write(f"{c[0]},{c[1]},{c[2]},{c[3]},{c[4]}")
        archivo.write("\n")

#Generando la tabla busquedas

W=GeneraBusquedas(productos,uuid,tipo_producto,fechas)

with open("busquedas.csv","w") as archivo:
    archivo.write("ci,producto,tipo_producto,fecha\n")
    for c in W:
        archivo.write(f"{c[0]},{c[1]},{c[2]},{c[3]}")
        archivo.write("\n")

import pandas as pd
T=pd.read_csv("ventas.csv")
T

cat clientes.csv

# Commented out IPython magic to ensure Python compatibility.
# %%R
# a = read.csv('ventas.csv')
# print(a)

# Commented out IPython magic to ensure Python compatibility.
# %%R
# as.data.frame(table(a$producto))

# Commented out IPython magic to ensure Python compatibility.
# %%R
# a.groupby(['ci','producto'])

# Commented out IPython magic to ensure Python compatibility.
# %%R
# library(party)
# 
# # Crea el input dataframe
# input.dat <-a
# 
# # Darle nombre a la imagen
# png(file = "arboli.png")
# 
# # Crear el arbol .
#   output.tree <- ctree(
#   nativeSpeaker ~ age + shoeSize + score, 
#   data = input.dat)
# 
# # PMuestra el arbol
# plot(output.tree)
# 
# # Salva elarchivo
# dev.off()























